version: '3.3'


services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: "book_project"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
      # - ${CONTAINERS_DATA_DIR_PATH}/database:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
      image: dpage/pgadmin4:6.2
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
        PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"
      # restart: unless-stopped
      # deploy:
      #   resources:
      #     limits:
      #       cpus: '0.5'
      #       memory: 1G
      networks:
        - app_network
  
  redis:
    image: redis:6.2
    container_name: redis
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]  # disable persistence
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      # - ${CONTAINERS_DATA_DIR_PATH}/rabbitmq/var:/var
      # - ${CONTAINERS_DATA_DIR_PATH}/rabbitmq/etc:/etc
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database:
  pgadmin:
  rabbitmq:
  redis:
