version: '3.3'


services:

  book_api:
    build:
      context: .
      dockerfile: BookApi/Dockerfile
    image: book_api:1.0.0
    container_name: book_api
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book_project
      - SPRING_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - app_network

  db_worker:
    build:
      context: .
      dockerfile: DbWorker/Dockerfile
    image: db_worker:1.0.0
    container_name: db_worker
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book_project
      - SPRING_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - app_network

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: "book_project"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
      image: dpage/pgadmin4:6.2
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
        PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - "5050:80"
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 1G
      networks:
        - app_network
  
  redis:
    image: redis:6.2
    container_name: redis
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]  # disable persistence
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database:
  pgadmin:
  rabbitmq:
  redis:
