name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build BookApi docker image
        run: docker build . --file BookApi/Dockerfile --tag book_api:$(date +%s)

      - name: build DbWorker docker image
        run: docker build . --file DbWorker/Dockerfile --tag db_worker:$(date +%s)